# Generated by Django 3.2.7 on 2021-10-01 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('numero_sala', models.CharField(max_length=5)),
                ('cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cines.cine')),
            ],
        ),
    ]
